/* Auto-generated by genmsg_cpp for file //home/nirav/Dropbox/PhD_at_WPI/AIMLab/daVinciGazeboPlugins/srv/SetJointState.srv */
#ifndef DAVINCIGAZEBOPLUGINS_SERVICE_SETJOINTSTATE_H
#define DAVINCIGAZEBOPLUGINS_SERVICE_SETJOINTSTATE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"

#include "sensor_msgs/JointState.h"



namespace daVinciGazeboPlugins
{
template <class ContainerAllocator>
struct SetJointStateRequest_ {
  typedef SetJointStateRequest_<ContainerAllocator> Type;

  SetJointStateRequest_()
  : joint_state()
  {
  }

  SetJointStateRequest_(const ContainerAllocator& _alloc)
  : joint_state(_alloc)
  {
  }

  typedef  ::sensor_msgs::JointState_<ContainerAllocator>  _joint_state_type;
   ::sensor_msgs::JointState_<ContainerAllocator>  joint_state;


  typedef boost::shared_ptr< ::daVinciGazeboPlugins::SetJointStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::daVinciGazeboPlugins::SetJointStateRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SetJointStateRequest
typedef  ::daVinciGazeboPlugins::SetJointStateRequest_<std::allocator<void> > SetJointStateRequest;

typedef boost::shared_ptr< ::daVinciGazeboPlugins::SetJointStateRequest> SetJointStateRequestPtr;
typedef boost::shared_ptr< ::daVinciGazeboPlugins::SetJointStateRequest const> SetJointStateRequestConstPtr;


template <class ContainerAllocator>
struct SetJointStateResponse_ {
  typedef SetJointStateResponse_<ContainerAllocator> Type;

  SetJointStateResponse_()
  : success(false)
  , status_message()
  {
  }

  SetJointStateResponse_(const ContainerAllocator& _alloc)
  : success(false)
  , status_message(_alloc)
  {
  }

  typedef uint8_t _success_type;
  uint8_t success;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_message_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  status_message;


  typedef boost::shared_ptr< ::daVinciGazeboPlugins::SetJointStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::daVinciGazeboPlugins::SetJointStateResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SetJointStateResponse
typedef  ::daVinciGazeboPlugins::SetJointStateResponse_<std::allocator<void> > SetJointStateResponse;

typedef boost::shared_ptr< ::daVinciGazeboPlugins::SetJointStateResponse> SetJointStateResponsePtr;
typedef boost::shared_ptr< ::daVinciGazeboPlugins::SetJointStateResponse const> SetJointStateResponseConstPtr;

struct SetJointState
{

typedef SetJointStateRequest Request;
typedef SetJointStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct SetJointState
} // namespace daVinciGazeboPlugins

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::daVinciGazeboPlugins::SetJointStateRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::daVinciGazeboPlugins::SetJointStateRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::daVinciGazeboPlugins::SetJointStateRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "9ca061465ef0ed08771ed240c43789f5";
  }

  static const char* value(const  ::daVinciGazeboPlugins::SetJointStateRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x9ca061465ef0ed08ULL;
  static const uint64_t static_value2 = 0x771ed240c43789f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::daVinciGazeboPlugins::SetJointStateRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "daVinciGazeboPlugins/SetJointStateRequest";
  }

  static const char* value(const  ::daVinciGazeboPlugins::SetJointStateRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::daVinciGazeboPlugins::SetJointStateRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
sensor_msgs/JointState joint_state\n\
\n\
================================================================================\n\
MSG: sensor_msgs/JointState\n\
# This is a message that holds data to describe the state of a set of torque controlled joints. \n\
#\n\
# The state of each joint (revolute or prismatic) is defined by:\n\
#  * the position of the joint (rad or m),\n\
#  * the velocity of the joint (rad/s or m/s) and \n\
#  * the effort that is applied in the joint (Nm or N).\n\
#\n\
# Each joint is uniquely identified by its name\n\
# The header specifies the time at which the joint states were recorded. All the joint states\n\
# in one message have to be recorded at the same time.\n\
#\n\
# This message consists of a multiple arrays, one for each part of the joint state. \n\
# The goal is to make each of the fields optional. When e.g. your joints have no\n\
# effort associated with them, you can leave the effort array empty. \n\
#\n\
# All arrays in this message should have the same size, or be empty.\n\
# This is the only way to uniquely associate the joint name with the correct\n\
# states.\n\
\n\
\n\
Header header\n\
\n\
string[] name\n\
float64[] position\n\
float64[] velocity\n\
float64[] effort\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::daVinciGazeboPlugins::SetJointStateRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::daVinciGazeboPlugins::SetJointStateResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::daVinciGazeboPlugins::SetJointStateResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::daVinciGazeboPlugins::SetJointStateResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "2ec6f3eff0161f4257b808b12bc830c2";
  }

  static const char* value(const  ::daVinciGazeboPlugins::SetJointStateResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x2ec6f3eff0161f42ULL;
  static const uint64_t static_value2 = 0x57b808b12bc830c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::daVinciGazeboPlugins::SetJointStateResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "daVinciGazeboPlugins/SetJointStateResponse";
  }

  static const char* value(const  ::daVinciGazeboPlugins::SetJointStateResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::daVinciGazeboPlugins::SetJointStateResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool success\n\
string status_message\n\
\n\
\n\
";
  }

  static const char* value(const  ::daVinciGazeboPlugins::SetJointStateResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::daVinciGazeboPlugins::SetJointStateRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.joint_state);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SetJointStateRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::daVinciGazeboPlugins::SetJointStateResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.success);
    stream.next(m.status_message);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SetJointStateResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<daVinciGazeboPlugins::SetJointState> {
  static const char* value() 
  {
    return "736fc197c94e4031ca128ae174d2c007";
  }

  static const char* value(const daVinciGazeboPlugins::SetJointState&) { return value(); } 
};

template<>
struct DataType<daVinciGazeboPlugins::SetJointState> {
  static const char* value() 
  {
    return "daVinciGazeboPlugins/SetJointState";
  }

  static const char* value(const daVinciGazeboPlugins::SetJointState&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<daVinciGazeboPlugins::SetJointStateRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "736fc197c94e4031ca128ae174d2c007";
  }

  static const char* value(const daVinciGazeboPlugins::SetJointStateRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<daVinciGazeboPlugins::SetJointStateRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "daVinciGazeboPlugins/SetJointState";
  }

  static const char* value(const daVinciGazeboPlugins::SetJointStateRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<daVinciGazeboPlugins::SetJointStateResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "736fc197c94e4031ca128ae174d2c007";
  }

  static const char* value(const daVinciGazeboPlugins::SetJointStateResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<daVinciGazeboPlugins::SetJointStateResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "daVinciGazeboPlugins/SetJointState";
  }

  static const char* value(const daVinciGazeboPlugins::SetJointStateResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // DAVINCIGAZEBOPLUGINS_SERVICE_SETJOINTSTATE_H

