controller_list:
  - name: fake_mtm_controller
    joints:
      - right_outer_yaw_joint
      - right_shoulder_pitch_joint
      - right_elbow_pitch_joint
      - right_wrist_platform_joint
      - right_wrist_pitch_joint
      - right_wrist_yaw_joint
      - right_wrist_roll_joint